server:
  port: 9092
spring:
  boot:
    admin:
      ui:
        title: Admin Console
      notify:
        mail:
          to: this.ischittaranjan@gmail.com
  mail:
      host: localhost
      port: 25

  security:
    user:
      name: admin
      password: admin



