server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/NBT/Git/configuration
  security:
    user:
      name: admin
      password: s3cr3t

  boot:
    admin:
      client:
        url: http://localhost:9092
        username: admin
        password: admin


  application:
    name: config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"

